import sharp from 'sharp';
import { encode } from 'blurhash';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const images = [
  '/images/IMG_4822.jpeg',
  '/images/IMG_4823.jpeg',
  '/images/IMG_4824.jpeg',
  '/images/IMG_4827.jpeg',
  '/images/IMG_4829.jpeg',
  '/images/commerce.jpeg',
];

async function getBlurhash(imgPath) {
  const filepath = join(root, 'public', imgPath);
  const { data, info } = await sharp(filepath)
    .resize(32, 32, { fit: 'inside' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  return encode(new Uint8ClampedArray(data), info.width, info.height, 4, 3);
}

const result = {};
for (const img of images) {
  try {
    result[img] = await getBlurhash(img);
    console.log(`✓ ${img} → ${result[img]}`);
  } catch (e) {
    console.error(`✗ ${img}: ${e.message}`);
  }
}

writeFileSync(
  join(root, 'src', 'imagePlaceholders.js'),
  `// Auto-generated by scripts/generateBlurhash.mjs — do not edit manually\nexport const LOCAL_BLURHASH = ${JSON.stringify(result, null, 2)};\n`
);

console.log('\nWrote src/imagePlaceholders.js');
