// Auto-generated by scripts/generateBlurhash.mjs — do not edit manually
export const LOCAL_BLURHASH = {
  "/images/IMG_4822.jpeg": "LiDTCjM|aJoc.AV[nzj=%hWYV@oJ",
  "/images/IMG_4823.jpeg": "LVDmHxIUjDkD?wRiV?t7.9RjV?t7",
  "/images/IMG_4824.jpeg": "LHC%X3Dij=og_NR4WBof.8ROkCbH",
  "/images/IMG_4827.jpeg": "LgED9wIUn$Rk.AWEV@WW%iWDWBWB",
  "/images/IMG_4829.jpeg": "LVD,Aq?wN#t8NhkYx]bJIVIoNHRj",
  "/images/commerce.jpeg": "LBD,7fRN01-:yZM^tSxu0hnz%Mog"
};
